development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

production: 
  <<: *default
  database: word-tracker-prod

test:
  <<: *default
  database: word-tracker-test
