development: &default
  template: template0
  adapter: postgresql
  encoding: unicode
  database: my-words_development
  pool: 5
  username: postgres
  password: ""
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || "3306" %>

production:
  <<: *default
  database: word-tracker-prod

test:
  <<: *default
  database: word-tracker-test
