development:
  adapter: sqlite3
  database: data/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: data/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: data/production.sqlite3
  pool: 5
  timeout: 5000
