require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WordsController do

  # This should return the minimal set of attributes required to create a valid
  # Word. As you add validations to Word, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all words as @words" do
      word = Word.create! valid_attributes
      get :index, {}, valid_session
      assigns(:words).should eq([word])
    end
  end

  describe "GET show" do
    it "assigns the requested word as @word" do
      word = Word.create! valid_attributes
      get :show, {:id => word.to_param}, valid_session
      assigns(:word).should eq(word)
    end
  end

  describe "GET new" do
    it "assigns a new word as @word" do
      get :new, {}, valid_session
      assigns(:word).should be_a_new(Word)
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested word" do
      word = Word.create! valid_attributes
      expect {
        delete :destroy, {:id => word.to_param}, valid_session
      }.to change(Word, :count).by(-1)
    end

    it "redirects to the words list" do
      word = Word.create! valid_attributes
      delete :destroy, {:id => word.to_param}, valid_session
      response.should redirect_to(words_url)
    end
  end
end
